### ISSUE TITLE
`window.onload` in efficient mode

### ISSUE THREAD

**Issue by andreyvolokitin** [JoviDeCroock/webpack-module-nomodule-plugin#11]
I was wondering how `load` event could affect TTI. AFAIK, `load` fires after all page resources are loaded, including images. Even if scripts are already preloaded with `modulepreload`, it seems like it might be too late for a script insertion, but I'm not sure...

Could `DOMContentLoaded` make any difference?

**Comment by JoviDeCroock** [comment]
That's a good question, I'll try to make time this weekend to research that!

**Comment by andreyvolokitin** [comment]
Another thing is, if it will be any different from just using `<script type="module">`, which works as `defer` (loads in parallel, doesn't block, gets executed on `DOMContentLoaded`). Also, it's not clear if `modulepreload` makes sense strictly in a context of "module/nomodule" pattern. It seems like it is more of a way to preload/parse/compile a tree of real modules, but in our case we just need to differentiate between 2 bundles... And seems like currently Blink is the only engine supporting  `modulepreload`: https://caniuse.com/#search=modulepreload

**Comment by JoviDeCroock** [comment]
In my tests it gave significant differences on chrome so I'd rather keep it for those reasons

**Comment by JoviDeCroock** [comment]
I've released this in 0.4.0
